### ISSUE TITLE
ModuleNotFoundError: No module named 'utils.composite'

### ISSUE THREAD

**Issue by Irdroid** [pulp-platform/pulp-freertos#4]
ModuleNotFoundError: No module named 'utils.composite' when running a gvsoc simulation.

Looks like some kind of custom python package. How can it be obtained?

```
pulp-freertos/support/egvsoc.sh --config-file=pulp@config_file=chips/pulp/pulp.json --platform=gvsoc \
	--dir=/home/georgi/pulp-freertos/hello_world/gvsim --binary=helloworld prepare run 
Traceback (most recent call last):
  File "./gwrap.py", line 33, in <module>
    retval = runner.run()
  File "/home/georgi/pulp-freertos/support/install/python/plp_runner.py", line 232, in run
    retval = platform.handleCommands()
  File "/home/georgi/pulp-freertos/support/install/python/plp_platform.py", line 64, in handleCommands
    if self.execCommand(command) != 0: return 1
  File "/home/georgi/pulp-freertos/support/install/python/plp_platform.py", line 70, in execCommand
    return getattr(self, cmd)()
  File "/home/georgi/pulp-freertos/support/install/python/vp_runner.py", line 1400, in run
    top_comp = time_engine.new(
  File "/home/georgi/pulp-freertos/support/install/python/vp_core.py", line 511, in new
    comp = self.get_component(component)(name, config, parent=self, debug=self.debug)
  File "/home/georgi/pulp-freertos/support/install/python/vp_core.py", line 489, in get_component
    return self.get_module(name).component
  File "/home/georgi/pulp-freertos/support/install/python/vp_core.py", line 485, in get_module
    module = imp.load_module(name, file, path, descr)
  File "/usr/lib/python3.8/imp.py", line 234, in load_module
    return load_source(name, filename, file)
  File "/usr/lib/python3.8/imp.py", line 171, in load_source
    module = _load(spec)
  File "<frozen importlib._bootstrap>", line 702, in _load
  File "<frozen importlib._bootstrap>", line 671, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 848, in exec_module
  File "<frozen importlib._bootstrap>", line 219, in _call_with_frames_removed
  File "/home/georgi/pulp-freertos/support/gvsoc/models/pulp/system.py", line 20, in <module>
    import utils.composite
ModuleNotFoundError: No module named 'utils.composite'
make: *** [/home/georgi/pulp-freertos/default_targets.mk:240: run-gvsoc] Error 
```

**Comment by Irdroid** [comment]
The error that I got was due to the fact that I had to manually download all the sub-modules as i got an error when checking out the sub-modules from this repository. 

The issue is that some of the python files inside the "support" directory are not set as executable, the simulation environment therefore does not compile and you will have the above error. To fix it you will have to chmod +x the needed python files in the "support" directory
